data vet_b;
	set vet_a (RENAME = (geography = _STATE));
RUN;
data brfss_a;
	set X.Chap10_1;
PROC SORT data = vet_b;
	by _STATE;
PROC SORT data = brfss_a;
	by _STATE;
RUN;
PROC FREQ data = brfss_a;
	tables _STATE;
RUN;
data brfss_b;
	merge brfss_a (IN = In1) vet_b (IN = In2);
	by _STATE;
	if (In1 = 1 and In2 = 1) then output brfss_b;
RUN;
PROC CONTENTS data = brfss_b VARNUM;
RUN;
PROC FREQ data = brfss_b;
	tables _STATE;
RUN;