data xwalk_b;
	set xwalk_a (RENAME = (State_FIPS = _STATE));
RUN;
PROC SORT data = xwalk_b;
	by _STATE;
RUN;
PROC FREQ data = brfss_b;
	tables _STATE;
RUN;
data brfss_c;
	merge brfss_b (IN = In1) xwalk_b (IN = In2);
	by _STATE;
	if (In1 = 1 and In2 = 1) then output brfss_c;
RUN;
PROC CONTENTS data = brfss_c VARNUM;
RUN;
PROC FREQ data = brfss_c;
	tables _STATE;
RUN;