LIBNAME other ODBC NOPROMPT="DSN=AHCA_database";
PROC SQL;
CONNECT TO ODBC (DATABASE= AHCA_database);
CREATE TABLE other.claims as SELECT * FROM WORK.claims;
EXECUTE (ALTER TABLE other.claims ALTER COLUMN blank_column CHAR(10)) BY ODBC;
DISCONNECT FROM ODBC;
