%MACRO state_freq1;
OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;
%LET selected_state = 12;
PROC FREQ data=brfss_a;
tables DIABETE3 /list missing;
WHERE _STATE = &selected_state;
title "PROC FREQ with _STATE=&&selected_state only";
run;
%MEND state_freq1;
%state_freq1;
%MACRO state_freq2(selected_state=);
OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;
PROC FREQ data=brfss_a;
tables DIABETE3 /list missing;
WHERE _STATE = &selected_state;
title "PROC FREQ with _STATE=&&selected_state only";
run;
%MEND state_freq2;
%state_freq2(selected_state=12);