data brfss_b;
	rename 	ASTHMA3 = CM1	CVDINFR4 = CM2		CVDCRHD4 = CM3
			CVDSTRK3 = CM4	CHCSCNCR = CM5		CHCOCNCR = CM6
			CHCCOPD1 = CM7	HAVARTH3 = CM8		ADDEPEV2 = CM9
			CHCKDNY1 = CM10	DIABETE3 = CM11;
	set brfss_a;
run;